# Generated by Django 5.1.2 on 2024-10-15 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_type', models.CharField(choices=[('First-Time', 'First-Time Investor'), ('Experienced', 'Experienced Investor')], max_length=20)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_to_invest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('income_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('term_investment', models.CharField(blank=True, max_length=50, null=True)),
                ('penny_stocks', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('government_policies', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('momentum', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6, null=True)),
                ('initial_investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('investment_goals', models.TextField(blank=True, null=True)),
                ('risk_tolerance', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6, null=True)),
                ('preferred_sectors', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
