# Generated by Django 5.1.2 on 2024-10-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentprofile',
            name='biggest_concern_other',
            field=models.CharField(default='No Concerns', max_length=255),
        ),
    ]
