# Generated by Django 5.1.2 on 2024-10-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_investmentprofile_biggest_concern_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentprofile',
            name='ongoing_investment_budget',
        ),
    ]
