# Generated by Django 5.1.2 on 2024-10-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_investmentprofile_ongoing_investment_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentprofile',
            name='biggest_concern_other',
            field=models.CharField(blank=True, default='No Concerns', max_length=255),
        ),
    ]
