# Generated by Django 5.1.2 on 2024-10-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_investmentprofile_biggest_concern_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentprofile',
            name='biggest_concern_other',
        ),
        migrations.AlterField(
            model_name='investmentprofile',
            name='biggest_concern',
            field=models.CharField(blank=True, choices=[('losing_money', 'Losing money'), ('not_understanding', 'Not understanding how it works'), ('volatility', 'Market volatility'), ('no', 'No Concerns.')], max_length=50, null=True),
        ),
    ]
